#!/bin/sh

#  ci_post_clone.sh
#  Xcode Cloud runs this right after cloning the repo, before resolving packages
#  or building.
#
#  Aeria's `.xcodeproj` is generated by XcodeGen from `project.yml` and is not
#  committed (see .gitignore). Without this, `xcodebuild` fails with
#  "Aeria.xcodeproj does not exist". So: install XcodeGen and generate the
#  project at the repo root.
#
#  Xcode Cloud also resolves Swift packages with automatic resolution OFF, so it
#  needs a committed Package.resolved *inside* the generated project. XcodeGen
#  never writes one, so we keep the pins at ci_scripts/Package.resolved and copy
#  them into place below. Regenerate that file (see its header comment) whenever
#  a package version in project.yml changes.

set -e

echo "--- ci_post_clone: generating Aeria.xcodeproj with XcodeGen ---"

# Homebrew is preinstalled on Xcode Cloud images; make sure it's on PATH.
if ! command -v brew >/dev/null 2>&1; then
    if [ -x /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [ -x /usr/local/bin/brew ]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

# Don't let Homebrew waste minutes auto-updating itself.
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

if ! command -v xcodegen >/dev/null 2>&1; then
    echo "Installing xcodegen…"
    brew install xcodegen
fi

xcodegen --version

# The script's working directory is ci_scripts/; generate at the repo root.
cd "${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
echo "Generating in: $(pwd)"
xcodegen generate --spec project.yml

echo "--- Generated ---"
ls -d Aeria.xcodeproj
ls -la Sources/App/Info.plist Sources/App/Aeria.entitlements \
       Sources/TopShelf/Info.plist Sources/TopShelf/AeriaTopShelf.entitlements

# Seed the SPM pins so Xcode Cloud doesn't try (and fail) to resolve from scratch.
RESOLVED_SRC="ci_scripts/Package.resolved"
RESOLVED_DST="Aeria.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
if [ ! -f "$RESOLVED_SRC" ]; then
    echo "error: $RESOLVED_SRC is missing — commit it (see its regeneration note)." >&2
    exit 1
fi
mkdir -p "$(dirname "$RESOLVED_DST")"
cp "$RESOLVED_SRC" "$RESOLVED_DST"
echo "--- Seeded $RESOLVED_DST ---"
cat "$RESOLVED_DST"
