#!/bin/sh

#  ci_post_clone.sh
#  Xcode Cloud runs this right after cloning the repo, before resolving packages
#  or building.
#
#  Aeria's `.xcodeproj` is generated by XcodeGen from `project.yml` and is not
#  committed (see .gitignore). Without this, `xcodebuild` fails with
#  "Aeria.xcodeproj does not exist". So: install XcodeGen and generate the
#  project at the repo root.

set -e

echo "--- ci_post_clone: generating Aeria.xcodeproj with XcodeGen ---"

# Homebrew is preinstalled on Xcode Cloud images; make sure it's on PATH.
if ! command -v brew >/dev/null 2>&1; then
    if [ -x /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [ -x /usr/local/bin/brew ]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

# Don't let Homebrew waste minutes auto-updating itself.
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

if ! command -v xcodegen >/dev/null 2>&1; then
    echo "Installing xcodegen…"
    brew install xcodegen
fi

xcodegen --version

# The script's working directory is ci_scripts/; generate at the repo root.
cd "${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
echo "Generating in: $(pwd)"
xcodegen generate --spec project.yml

echo "--- Generated ---"
ls -d Aeria.xcodeproj
ls -la Sources/App/Info.plist Sources/App/Aeria.entitlements \
       Sources/TopShelf/Info.plist Sources/TopShelf/AeriaTopShelf.entitlements
